# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-11 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralFV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potencia_de_planta_fv', models.DecimalField(decimal_places=2, max_digits=50)),
                ('nombre_proyecto', models.CharField(max_length=255)),
                ('temperatura_ambiente', models.IntegerField()),
                ('minima_temperatura_ambiente_esperada', models.IntegerField()),
                ('tipo_de_inversor', models.CharField(max_length=40)),
                ('lugar_instalacion_opcion_techo_cubierta', models.CharField(max_length=40, null=True)),
                ('tipo_servicio', models.CharField(max_length=40)),
                ('voltage_servicio', models.CharField(max_length=40)),
                ('lugar_instalacion', models.CharField(max_length=40)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mppt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('numero_de_cadenas_en_paralelo', models.IntegerField()),
                ('numero_de_paneles_en_serie_por_cadena', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PanelFV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=40)),
                ('fabricante_1', models.CharField(max_length=40)),
                ('model_panel_solar_1', models.CharField(max_length=40)),
                ('modelo_panel_solar_2', models.CharField(max_length=40)),
                ('fabricante_2', models.CharField(max_length=40)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BaseCableado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=255)),
                ('tipo_alambrado', models.CharField(max_length=40)),
                ('tipo_conductor', models.CharField(max_length=40, null=True)),
                ('distancia_del_conductor_mas_largo', models.IntegerField()),
                ('caida_de_tension_de_diseno', models.IntegerField()),
                ('tipo_canalizacion', models.CharField(max_length=40, null=True)),
                ('canalizacion', models.CharField(max_length=40, null=True)),
                ('tamanio_canalizacion', models.IntegerField(null=True)),
                ('material_conductor', models.CharField(max_length=40)),
                ('disenio_bandeja', models.CharField(max_length=40, null=True)),
                ('material_bandeja', models.CharField(max_length=40, null=True)),
                ('tipo_acabado', models.CharField(max_length=40, null=True)),
                ('tapa_superior_bandeja_portacable', models.NullBooleanField()),
                ('tapa_inferior_bandeja_portacable', models.NullBooleanField()),
                ('perfiles_separadores', models.NullBooleanField()),
                ('longitud_tramo', models.CharField(max_length=40, null=True)),
                ('ancho_mm', models.CharField(max_length=40, null=True)),
                ('maximo_numero_de_conductores', models.IntegerField()),
                ('alto_mm', models.CharField(max_length=40, null=True)),
                ('tipo_carga', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cableado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuente', to='cotizadorFV.BaseCableado')),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salida', to='cotizadorFV.BaseCableado')),
            ],
        ),
    ]
