# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-11 21:28
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('identificacion', models.IntegerField()),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('cotizador', 'Cotizador'), ('ingeniero', 'Ingeniero')], default='cotizador', max_length=24)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avatar/')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
